basePath: /
consumes:
  - application/json
definitions: {}
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
host: 'localhost:4100'
info:
  contact:
    email: edprietov@unal.edu.co
    name: Edisson Prieto
  description: This is a microservice exposed as an API Rest coded in Elixir
  termsOfService: 'http://swagger.io/terms/'
  title: Wallet-Transaction API
  version: '1.0'
paths:
  /transaction:
    get:
      description: For show all created transactions
      operationId: TransactionWeb.TransController.index
      parameters:
        - description: Number of elements per page
          in: query
          minimum: 1
          name: page_size
          required: false
          type: integer
        - description: Number of the page
          in: query
          minimum: 1
          name: page
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Not found
      summary: Get list of all transactions
      tags:
        - transaction
    post:
      description: This can attempt to carry out a transaction and if it is valid it will update the specified wallet
      operationId: TransactionWeb.TransController.create
      parameters:
        - description: Number of elements per page
          in: query
          minimum: 1
          name: page_size
          required: false
          type: integer
        - description: Number of the page
          in: query
          minimum: 1
          name: page
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Not found
      summary: Try to make a transaction
      tags:
        - transaction
  /wallet:
    get:
      description: For show all created wallets
      operationId: TransactionWeb.WalletController.index
      parameters:
        - description: Number of elements per page
          in: query
          minimum: 1
          name: page_size
          required: false
          type: integer
        - description: Number of the page
          in: query
          minimum: 1
          name: page
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Not found
      summary: Get list of all wallets
      tags:
        - wallet
    post:
      description: This can create a wallet for a logged user
      operationId: TransactionWeb.WalletController.create
      parameters:
        - description: Number of elements per page
          in: query
          minimum: 1
          name: page_size
          required: false
          type: integer
        - description: Number of the page
          in: query
          minimum: 1
          name: page
          required: false
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Not found
      summary: Create a wallet
      tags:
        - wallet
  '/wallet/{id}':
    get:
      description: For search an specific wallet
      operationId: TransactionWeb.WalletController.show
      parameters:
        - description: Number of elements per page
          in: query
          minimum: 1
          name: page_size
          required: false
          type: integer
        - description: Number of the page
          in: query
          minimum: 1
          name: page
          required: false
          type: integer
        - description: WalletID
          in: path
          name: id
          required: true
          type: integer
          x-example: 1
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Not found
      summary: Get wallet by its id
      tags:
        - wallet
produces:
  - application/json
schemes:
  - http
  - https
swagger: '2.0'
tags:
  - description: Everything related to wallet's management
    externalDocs:
      description: Path
      url: 'http://localhost:4100/wallet'
    name: wallet
  - description: Everything related to transaction's management
    externalDocs:
      description: Path
      url: 'http://localhost:4100/transaction'
    name: transaction
