basePath: /
consumes:
  - application/json
definitions:
  Transaction:
    description: A transaction made by an user
    example:
      id_method_payment: 1
      mount: 3000
      token: algo
      transaction_id: 10
      type: 1
      user_id: 1
    properties:
      id_method_payment:
        description: In case of wallet recharging is used to identify methos user for payment
        type: integer
      mount:
        description: Amount of transaction
        type: integer
      token:
        description: To verify wallet correspondence
        type: string
      transaction_id:
        description: Unique identifier of a transaction
        type: string
      type:
        description: Identify the kind of transaction
        type: integer
      user_id:
        description: User who make a transaction
        type: integer
    required:
      - user_id
      - transaction_id
    title: Transaction
    type: object
  Transactions:
    description: A collection of transactions
    items:
      $ref: '#/definitions/Transaction'
    title: Transactions
    type: array
  Wallet:
    description: A wallet related to a user
    example:
      balance: 10000
      token: DU7342w98weujafbsaxvw324734w
      user_id: 5
      wallet_id: 4
    properties:
      balance:
        description: Wallet balance
        type: integer
      token:
        description: Wallet token
        type: string
      user_id:
        description: Owner of the wallet
        type: integer
      wallet_id:
        description: Unique identifier of a wallet
        type: string
    required:
      - user_id
      - wallet_id
    title: Wallet
    type: object
  Wallets:
    description: A collection of Wallets
    items:
      $ref: '#/definitions/Wallet'
    title: Wallets
    type: array
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
host: 'localhost:4100'
info:
  contact:
    email: edprietov@unal.edu.co
    name: Edisson Prieto
  description: This is a microservice exposed as an API Rest coded in Elixir
  termsOfService: 'http://swagger.io/terms/'
  title: Wallet-Transaction API
  version: '1.0'
paths:
  /transaction:
    get:
      description: For show all created transactions
      operationId: TransactionWeb.TransController.index
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Not found
      summary: Get list of all transactions
      tags:
        - transaction
    post:
      description: This can attempt to carry out a transaction and if it is valid it will update the specified wallet
      operationId: TransactionWeb.TransController.create
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Not found
      summary: Try to make a transaction
      tags:
        - transaction
  /wallet:
    get:
      description: For show all created wallets
      operationId: TransactionWeb.WalletController.index
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Wallets'
        '400':
          description: Not found
      summary: Get list of all wallets
      tags:
        - wallet
    post:
      description: This can create a wallet for a logged user
      operationId: TransactionWeb.WalletController.create
      parameters: []
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Wallet'
        '400':
          description: Not found
      summary: Create a wallet
      tags:
        - wallet
  '/wallet/{id}':
    get:
      description: For search an specific wallet
      operationId: TransactionWeb.WalletController.show
      parameters:
        - description: WalletID
          in: path
          name: id
          required: true
          type: integer
          x-example: 1
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Wallet'
        '400':
          description: Not found
      summary: Get wallet by its id
      tags:
        - wallet
produces:
  - application/json
schemes:
  - http
  - https
swagger: '2.0'
tags:
  - description: Everything related to wallet's management
    externalDocs:
      description: Path
      url: 'http://localhost:4100/wallet'
    name: wallet
  - description: Everything related to transaction's management
    externalDocs:
      description: Path
      url: 'http://localhost:4100/transaction'
    name: transaction
